In [2]:
import pandas as pd
ingr_per_group= pd.read_csv('tabellen/ingr_per_group(1).csv')
data_ingr=pd.read_csv('tabellen/data_ingr.csv')
ingr_group3 = ingr_per_group[(ingr_per_group['group'] == 3)]

In [3]:
ingr_group3

     Unnamed: 0                                         ingredient  group
528         528                                Mutti polpa in blik      3
529         529         Mutti pomodoro San Marzano tomaten in blik      3
530         530                             Nederlandse trostomaat      3
531         531  Nielsen Massey Madagascar bourbon vanille-extract      3
532         532         No Fairytales paprika &amp; chili tortilla      3
..          ...                                                ...    ...
786         786                                        appelstroop      3
787         787                                      arachide olie      3
788         788                                       arachideolie      3
789         789                                   arrabbiata pesto      3
790         790                                           artisjok      3

[263 rows x 3 columns]

In [4]:
data_ingr

,Unnamed: 0,recipe,ingredient,quantity,unit
0,0,Kruidnoten met choco-discodip,melkchocolade,100.0,g
1,1,Kruidnoten met choco-discodip,kruidnoten,100.0,g
2,2,Kruidnoten met choco-discodip,discodip,2.0,el
3,3,Kruidnoten in marsepein,blanke marsepein,150.0,g
4,4,Kruidnoten in marsepein,ongezouten roomboter,15.0,g
...,...,...,...,...,...
49814,71804,Biefstuk met rodewijnsaus en ham,olijfolie,4.0,el
49815,71805,Biefstuk met rodewijnsaus en ham,biefstukken,4.0,NaN
49816,71806,Biefstuk met rodewijnsaus en ham,boter,25.0,g
49817,71807,Biefstuk met rodewijnsaus en ham,serranoham,4.0,plakken
49818,71808,Biefstuk met rodewijnsaus en ham,rode wijn,200.0,ml

In [5]:
onze = data_ingr[data_ingr['ingredient'].isin(ingr_group3['ingredient'])]
onze

,Unnamed: 0,recipe,ingredient,quantity,unit
20,20,Pepernotentaart met marsepeinstrik,aardbeienjam,2.0,el
66,78,Ajam pangang,arachideolie,2.0,el
93,117,Bloemkoolschotel,aardappelschijfjes,600.0,g
95,119,Tartelettes,amandelmeel,30.0,g
120,144,Sajoer boontjes,arachideolie,1.0,el
...,...,...,...,...,...
49731,71669,Kip uit de braadzak,aardappelballetjes,600.0,g
49751,71719,Thaise kipcurry met aubergine,Thaise kipfiletblokjes met citroengras,1.0,schaal
49755,71737,Appel-ananassap,ananas,1.0,NaN
49784,71769,Mosselen op z'n Thais,Thaise vissaus,1.0,el
49804,71789,Peren-amandelcoupe,amandelschaafsel,1.0,el

In [6]:
onze

,Unnamed: 0,recipe,ingredient,quantity,unit
20,20,Pepernotentaart met marsepeinstrik,aardbeienjam,2.0,el
66,78,Ajam pangang,arachideolie,2.0,el
93,117,Bloemkoolschotel,aardappelschijfjes,600.0,g
95,119,Tartelettes,amandelmeel,30.0,g
120,144,Sajoer boontjes,arachideolie,1.0,el
...,...,...,...,...,...
49731,71669,Kip uit de braadzak,aardappelballetjes,600.0,g
49751,71719,Thaise kipcurry met aubergine,Thaise kipfiletblokjes met citroengras,1.0,schaal
49755,71737,Appel-ananassap,ananas,1.0,NaN
49784,71769,Mosselen op z'n Thais,Thaise vissaus,1.0,el
49804,71789,Peren-amandelcoupe,amandelschaafsel,1.0,el

In [7]:
onze.unit.value_counts()

unit
g                    882
el                   714
ml                   145
tl                    49
kg                    41
schaal                29
liter                 29
zak                    9
struik                 8
zakje                  5
krop                   4
bakje                  4
plakje                 3
bak                    3
pakje                  3
stukje                 3
blik                   3
blikje                 3
bakjes                 3
plak                   3
cupje                  2
stuk                   2
stronk                 2
sneetje                2
pak                    2
plakken                2
zakjes                 2
vel                    2
flesje                 2
friszoete stevige      1
bol                    1
friszure               1
kruimige               1
potje                  1
schaaltjes             1
grote                  1
zakken                 1
doos                   1
x 750 g                1
friszoete              1
x 4 plakken            1
Name: count, dtype: int64

In [8]:
onze[onze.unit == 'liter'].ingredient.value_counts()

ingredient
arachideolie         27
amandelmelk           1
Spaanse rode wijn     1
Name: count, dtype: int64

In [9]:
alle_units = set(onze['unit'])
alle_units

{'bak',
 'bakje',
 'bakjes',
 'blik',
 'blikje',
 'bol',
 'cupje',
 'doos',
 'el',
 'flesje',
 'friszoete',
 'friszoete stevige',
 'friszure',
 'g',
 'grote',
 'kg',
 'krop',
 'kruimige',
 'liter',
 'ml',
 nan,
 'pak',
 'pakje',
 'plak',
 'plakje',
 'plakken',
 'potje',
 'schaal',
 'schaaltjes',
 'sneetje',
 'stronk',
 'struik',
 'stuk',
 'stukje',
 'tl',
 'vel',
 'x 4 plakken',
 'x 750 g',
 'zak',
 'zakje',
 'zakjes',
 'zakken'}

In [10]:
import pandas as pd

convert_tabel = [
    ['el', 10],
    ['ml', 0.92], 
    ['tl', 2], 
    ['kg', 1000], 
    ['schaal', 380], 
    ['liter', 920],
    ['zak', 1000],
    ['struik', 900],
    ['zakje', 950],
    ['krop', 800],
    ['bakje', 850],
    ['plakje', 50],
    ['bak', 700],
    ['pakje', 90],
    ['stukje', 80],
    ['blik', 920],
    ['blikje', 85],
    ['bakjes', 870],
    ['plak', 65],
    ['cupje', 70],
    ['stuk', 950],
    ['stronk', 850],
    ['sneetje', 55],
    ['pak', 700],
    ['plakken', 60],
    ['zakjes', 960],
    ['vel', 70],
    ['flesje', 780],
    ['friszoete stevige', 1020],
    ['bol', 920],
    ['friszure', 1000],
    ['kruimige', 980],
    ['potje', 850],
    ['schaaltjes', 910],
    ['grote', 900],
    ['zakken', 1100],
    ['doos', 1000],
    ['x 750 g', 750],
    ['friszoete', 1040],
    ['x 4 plakken', 400]
]

convert_df = pd.DataFrame(convert_tabel, columns=['Eenheid', 'keer'])

In [11]:
convert_df

              Eenheid     keer
0                  el    10.00
1                  ml     0.92
2                  tl     2.00
3                  kg  1000.00
4              schaal   380.00
5               liter   920.00
6                 zak  1000.00
7              struik   900.00
8               zakje   950.00
9                krop   800.00
10              bakje   850.00
11             plakje    50.00
12                bak   700.00
13              pakje    90.00
14             stukje    80.00
15               blik   920.00
16             blikje    85.00
17             bakjes   870.00
18               plak    65.00
19              cupje    70.00
20               stuk   950.00
21             stronk   850.00
22            sneetje    55.00
23                pak   700.00
24            plakken    60.00
25             zakjes   960.00
26                vel    70.00
27             flesje   780.00
28  friszoete stevige  1020.00
29                bol   920.00
30           friszure  1000.00
31           kruimige   980.00
32              potje   850.00
33         schaaltjes   910.00
34              grote   900.00
35             zakken  1100.00
36               doos  1000.00
37            x 750 g   750.00
38          friszoete  1040.00
39        x 4 plakken   400.00

In [12]:
df_onze=onze.merge(convert_df, how='left', left_on='unit', right_on='Eenheid')

In [13]:
df_onze.keer=df_onze.keer.fillna(1)

In [14]:
df_onze.quantity=df_onze.quantity * df_onze.keer

In [15]:
df_onze.unit='g'

In [16]:
df_onze=df_onze.drop(columns=['Eenheid','keer'])

In [17]:
df_onze['ingredient'] = df_onze['ingredient'].str.lower()

In [18]:
data_ingr[data_ingr['Unnamed: 0'] == 20]

,Unnamed: 0,recipe,ingredient,quantity,unit
20,20,Pepernotentaart met marsepeinstrik,aardbeienjam,2.0,el

In [19]:
data_ingr.update(df_onze)

In [20]:
data_ingr

,Unnamed: 0,recipe,ingredient,quantity,unit
0,20,Pepernotentaart met marsepeinstrik,aardbeienjam,20.0,g
1,78,Ajam pangang,arachideolie,20.0,g
2,117,Bloemkoolschotel,aardappelschijfjes,600.0,g
3,119,Tartelettes,amandelmeel,30.0,g
4,144,Sajoer boontjes,arachideolie,10.0,g
...,...,...,...,...,...
49814,71804,Biefstuk met rodewijnsaus en ham,olijfolie,4.0,el
49815,71805,Biefstuk met rodewijnsaus en ham,biefstukken,4.0,NaN
49816,71806,Biefstuk met rodewijnsaus en ham,boter,25.0,g
49817,71807,Biefstuk met rodewijnsaus en ham,serranoham,4.0,plakken
49818,71808,Biefstuk met rodewijnsaus en ham,rode wijn,200.0,ml

In [21]:
data_ingr.shape

(49819, 5)

In [22]:
data_ingr.unit.value_counts()

unit
g              21206
el              8013
ml              2888
tl              2832
teen            1315
               ...
x 2                1
tenen,             1
x 75 g             1
x 2 kg             1
middelgrote        1
Name: count, Length: 132, dtype: int64

In [23]:
#zoeken naar trefwoorden en o.b.v samenvoeg groep by voor stap 2

In [24]:
df_onze.ingredient.value_counts()

ingredient
arachideolie                           489
parmigiano reggiano                    151
amandelschaafsel                        83
tasty tom trostomaat                    72
parmezaanse kaas                        65
                                      ...
afbakbagel                               1
vanka kawat diepvries purutblaadjes      1
spaanse rode peper                       1
thaise groene currypasta                 1
riesling witte wijn                      1
Name: count, Length: 263, dtype: int64

In [25]:
a = df_onze.ingredient.value_counts().reset_index().rename(columns={"index": "value", 0: "count"})
a[:50]

                             ingredient  count
0                          arachideolie    489
1                   parmigiano reggiano    151
2                      amandelschaafsel     83
3                  tasty tom trostomaat     72
4                      parmezaanse kaas     65
5                           ahornsiroop     59
6                       pecorino romano     56
7                           aardappelen     52
8                       appelciderazijn     52
9                             aardbeien     34
10       ansjovisfilets in olie in blik     34
11                          amandelmeel     27
12           parmigiano reggiano-poeder     25
13             aardappelpuree met boter     22
14                         amandelspijs     21
15                               ananas     20
16                   saitaku rijstazijn     18
17                          appelstroop     17
18          ansjovisfilets in olijfolie     17
19                    thaise wokgroente     16
20                     aardappelpartjes     16
21                      shanghai paksoi     16
22                       zaanse mosterd     14
23                       ansjovisfilets     12
24                   aardappelschijfjes     12
25                       turkse yoghurt     11
26                             appelsap     10
27                    thaise roerbakmix     10
28                          amandelmelk     10
29                            achterham      9
30                       taggia olijven      9
31  zaanse hoeve geraspte kaas mild 30+      9
32           parmigiano reggiano-flakes      9
33                             aardpeer      8
34                                appel      8
35           aardappelpartjes met schil      8
36                     tabasco chipotle      8
37                       taggia-olijven      8
38      thaise zilvervliesrijst noedels      8
39                                aioli      8
40     ambachtelijk gerookt ontbijtspek      8
41                         abrikozenjam      8
42                     zaanse mayonaise      8
43                        taleggio kaas      7
44                             amaretto      7
45                puur natuur kokosrasp      7
46                      pink lady appel      7
47                 zeeuwse keukenstroop      7
48                         amandelpasta      7
49                         oreo-koekjes      7

In [29]:
[word for word in a["ingredient"] if "aardappel" in word]

['aardappelen',
 'aardappelpuree met boter',
 'aardappelpartjes',
 'aardappelschijfjes',
 'aardappelpartjes met schil',
 'pommes primeur aardappelen',
 'opperdoezer ronde aardappelen',
 'aardappel',
 'aardappelzetmeel',
 'aardappelen iets kruimig',
 'aardappelballetjes',
 'provençaalse aardappelpartjes met schil',
 'aardappelrösties',
 'aardappelpuree (koelvers)',
 'toscaanse aardappelpartjes',
 'aardappelsalade',
 'aardappelpuree',
 'aardappelkroketjes',
 'aardappel eigenheimer']

In [38]:
tomaat_t = ("tomaat", set([word for word in df_onze["ingredient"] if "toma" in word and "blik" not in word]))
parma_t = ("parmezaanse kaas", set([word for word in df_onze["ingredient"] if "parm" in word and "prosciutto" not in word]))
paprika_t = ("paprika", set([word for word in df_onze["ingredient"] if "paprika" in word]))
paturain_t = ("paturain", set([word for word in df_onze["ingredient"] if "paturain" in word]))
olijven_t = ("olijven", set([word for word in df_onze["ingredient"] if "olij" in word and "olie" not in word]))
olijfolie_t = ("olijfolie", set([word for word in df_onze["ingredient"] if "olijfolie" in word]))
oreo_t = ("oreo", set([word for word in df_onze["ingredient"] if "oreo" in word]))
#aardappel = set([word for word in df_onze["ingredient"] if "aardappel" == word])
ciabatta_t = ("ciabatta", set([word for word in df_onze["ingredient"] if "ciaba" in word]))
arachide_t = ("arachide", set([word for word in df_onze["ingredient"] if "arachide" in word]))
framboos_t = ("framboos", set([word for word in df_onze["ingredient"] if "framboos" in word]))
sp_peper_t = ("spaanse peper", set([word for word in df_onze["ingredient"] if "spaanse peper" in word]))
mayo_t = ("mayonaise", set([word for word in df_onze["ingredient"] if "mayo" in word]))

ingr_tuple_lijst = [tomaat_t, parma_t, paprika_t, paturain_t, olijven_t, olijfolie_t, oreo_t, ciabatta_t, framboos_t, sp_peper_t, mayo_t]

for x in df_onze["ingredient"]:
    for y in ingr_tuple_lijst:
        if x in y[1]:
            df_onze["ingredient"].replace(x, y[0], inplace=True)