In [21]:
import pandas as pd
ingr_per_group= pd.read_csv('tabellen/ingr_per_group(1).csv')
data_ingr=pd.read_csv('tabellen/data_ingr.csv')
ingr_group3 = ingr_per_group[(ingr_per_group['group'] == 3)]

In [27]:
data_ingr

,Unnamed: 0,recipe,ingredient,quantity,unit
0,0,Kruidnoten met choco-discodip,melkchocolade,100.0,g
1,1,Kruidnoten met choco-discodip,kruidnoten,100.0,g
2,2,Kruidnoten met choco-discodip,discodip,2.0,el
3,3,Kruidnoten in marsepein,blanke marsepein,150.0,g
4,4,Kruidnoten in marsepein,ongezouten roomboter,15.0,g
...,...,...,...,...,...
49814,71804,Biefstuk met rodewijnsaus en ham,olijfolie,4.0,el
49815,71805,Biefstuk met rodewijnsaus en ham,biefstukken,4.0,NaN
49816,71806,Biefstuk met rodewijnsaus en ham,boter,25.0,g
49817,71807,Biefstuk met rodewijnsaus en ham,serranoham,4.0,plakken
49818,71808,Biefstuk met rodewijnsaus en ham,rode wijn,200.0,ml

In [28]:
ingr_group3

     Unnamed: 0                                         ingredient  group
528         528                                Mutti polpa in blik      3
529         529         Mutti pomodoro San Marzano tomaten in blik      3
530         530                             Nederlandse trostomaat      3
531         531  Nielsen Massey Madagascar bourbon vanille-extract      3
532         532         No Fairytales paprika &amp; chili tortilla      3
..          ...                                                ...    ...
786         786                                        appelstroop      3
787         787                                      arachide olie      3
788         788                                       arachideolie      3
789         789                                   arrabbiata pesto      3
790         790                                           artisjok      3

[263 rows x 3 columns]

In [36]:
onze = data_ingr[data_ingr['ingredient'].isin(ingr_group3['ingredient'])]
onze

,Unnamed: 0,recipe,ingredient,quantity,unit
20,20,Pepernotentaart met marsepeinstrik,aardbeienjam,2.0,el
66,78,Ajam pangang,arachideolie,2.0,el
93,117,Bloemkoolschotel,aardappelschijfjes,600.0,g
95,119,Tartelettes,amandelmeel,30.0,g
120,144,Sajoer boontjes,arachideolie,1.0,el
...,...,...,...,...,...
49731,71669,Kip uit de braadzak,aardappelballetjes,600.0,g
49751,71719,Thaise kipcurry met aubergine,Thaise kipfiletblokjes met citroengras,1.0,schaal
49755,71737,Appel-ananassap,ananas,1.0,NaN
49784,71769,Mosselen op z'n Thais,Thaise vissaus,1.0,el
49804,71789,Peren-amandelcoupe,amandelschaafsel,1.0,el

In [37]:
alle_units = set(onze['unit'])
alle_units

{'bak',
 'bakje',
 'bakjes',
 'blik',
 'blikje',
 'bol',
 'cupje',
 'doos',
 'el',
 'flesje',
 'friszoete',
 'friszoete stevige',
 'friszure',
 'g',
 'grote',
 'kg',
 'krop',
 'kruimige',
 'liter',
 'ml',
 nan,
 'pak',
 'pakje',
 'plak',
 'plakje',
 'plakken',
 'potje',
 'schaal',
 'schaaltjes',
 'sneetje',
 'stronk',
 'struik',
 'stuk',
 'stukje',
 'tl',
 'vel',
 'x 4 plakken',
 'x 750 g',
 'zak',
 'zakje',
 'zakjes',
 'zakken'}